---
name: Go
on:
  pull_request:
  push:
    branches:
      - main
      - "release-*"

# Minimal permissions to be inherited by any job that don't declare it's own permissions
permissions:
  contents: read

jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest

    strategy:
      matrix:
        go_version: ["1.19", "1.20", "1.21"]

    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Set up Go ${{ matrix.go_version }}
        uses: actions/setup-go@41dfa10bad2bb2ae585af6ee5bb4d7d973ad74ed # v5.1.0
        with:
          go-version: ${{ matrix.go_version }}

      - name: Cache Go modules
        id: cache
        uses: actions/cache@6849a6489940f00c2f30c0fb92c6274307ccb58a # v4.1.2
        with:
          path: ~/go/pkg/mod
          key: v1-go${{ matrix.go_version }}

      - name: Run tests and check license
        run: make check_license test
        env:
          CI: true

      - name: Run style and unused
        if: ${{ matrix.go_version == '1.20' }}
        run: make style unused
