---
name: Go
on:
  pull_request:
  push:
    branches:
      - main
      - "release-*"

# Minimal permissions to be inherited by any job that don't declare it's own permissions
permissions:
  contents: read

jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest

    strategy:
      matrix:
        go_version: ["1.19", "1.20", "1.21"]

    steps:
      - name: Checkout code
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: Set up Go ${{ matrix.go_version }}
        uses: actions/setup-go@cdcb36043654635271a94b9a6d1392de5bb323a7 # v5.0.1
        with:
          go-version: ${{ matrix.go_version }}

      - name: Cache Go modules
        id: cache
        uses: actions/cache@0c45773b623bea8c8e75f6c82b208c3cf94ea4f9 # v4.0.2
        with:
          path: ~/go/pkg/mod
          key: v1-go${{ matrix.go_version }}

      - name: Run tests and check license
        run: make check_license test
        env:
          CI: true

      - name: Run style and unused
        if: ${{ matrix.go_version == '1.20' }}
        run: make style unused
